#!/usr/bin/env bash
#
# glm52-runtime-patch.sh
# ===========================================================================
# Runtime reconstruction of the TWO non-vendored CosmicRaisins / eugr mods,
# applied INSIDE each GLM-5.2-NVFP4 container ONCE, BEFORE `vllm serve`:
#
#   STEP A  glm52-sm12x-sparse  (Task A — VALIDATED against vLLM @ ab66606)
#     - make the runtime-mounted deepseek_v4_ops/*.py importable
#       (create the package __init__.py upstream does not ship)
#     - patch vllm/utils/deep_gemm.py so on capability family 120 (sm_12x / GB10)
#       fp8_fp4_mqa_logits / fp8_fp4_paged_mqa_logits / tf32_hc_prenorm_gemm
#       short-circuit to the sm12x_* Triton fallbacks BEFORE the DeepGEMM
#       _missing() gate
#     - patch vllm/model_executor/layers/sparse_attn_indexer.py so the
#       SparseAttnIndexer ctor never requires has_deep_gemm() on sm_121
#
#   STEP B  glm52-b12x-sparse  (Task B)
#     - pip install --no-deps b12x==0.23.0 (pure py3-none-any wheel; CuTe DSL
#       kernels JIT at runtime; --no-deps so it does not clobber the pinned
#       cutlass-dsl / torch stack)
#     - PROBE the real import and decide cudagraph mode from it (not from the env
#       var): import OK -> GLM52_B12X_MLA=1 + cudagraph FULL; import FAIL ->
#       GLM52_B12X_MLA=0 + cudagraph PIECEWISE (the Triton decode fallback does
#       torch.full(device=...) which is illegal under graph capture)
#     - the fused_indexer score-mode patch is INTENTIONALLY OMITTED: it is not
#       vendored, it is optional (a perf swap, not correctness — the in-tree
#       sm12x Triton indexer handles correctness via GLM52_*_TRITON), and b12x's
#       fused_indexer already DEFAULTS to IndexerScoreMode.NSA_RELU_SUM /
#       IndexerOutputMode.TOKEN_LOGITS (the GLM-5.2 NSA mode). Add it later as a
#       perf step only.
#
# Idempotent. The result of the probe (GLM52_B12X_MLA + GLM52_CUDAGRAPH_MODE) is
# written to /workspace/glm52-b12x.env so the launcher's `vllm serve` step can
# source it and pick FULL vs PIECEWISE from REAL import success.
#
# Run as the FIRST thing in every container (head + all 7 workers), after the
# kernel mounts are in place, before `vllm serve`. License: Apache-2.0.
# ===========================================================================
set -euo pipefail

PYDIST="${GLM52_VLLM_DIST:-/usr/local/lib/python3.12/dist-packages}"
VLLM="$PYDIST/vllm"
DEEP_GEMM="$VLLM/utils/deep_gemm.py"
INDEXER="$VLLM/model_executor/layers/sparse_attn_indexer.py"
OPS_PKG="$VLLM/v1/attention/ops/deepseek_v4_ops"
B12X_VERSION="${GLM52_B12X_VERSION:-0.23.0}"
B12X_ENV_OUT="${GLM52_B12X_ENV_OUT:-/workspace/glm52-b12x.env}"

# ===========================================================================
# STEP A — glm52-sm12x-sparse  (VALIDATED; do not edit the rewriter logic)
# ===========================================================================
echo "== glm52-sm12x-sparse: reconstructing mod (vllm dist: $PYDIST)"

# A1 — make the mounted deepseek_v4_ops kernels importable. mla/ is already a
# package upstream; only deepseek_v4_ops needs the marker. The bind-mounted .py
# files are RO but the directory itself is writable.
if [ ! -f "$OPS_PKG/__init__.py" ]; then
  mkdir -p "$OPS_PKG"
  printf '# auto-generated by glm52-sm12x-sparse patch (package marker)\n' \
    > "$OPS_PKG/__init__.py"
  echo "   created $OPS_PKG/__init__.py"
else
  echo "   $OPS_PKG/__init__.py already present"
fi
for f in sm12x_deep_gemm_fallbacks.py sm12x_mqa.py b12x_sparse_helpers.py; do
  if [ -f "$OPS_PKG/$f" ]; then
    echo "   ok mounted: deepseek_v4_ops/$f"
  else
    echo "   WARNING: deepseek_v4_ops/$f is NOT mounted — launcher KMOUNTS missing?" >&2
  fi
done

# A2 & A3 — in-place source patches via an anchored Python rewriter (idempotent
# via a sentinel; each anchor checked so a future re-pin surfaces immediately).
DEEP_GEMM="$DEEP_GEMM" INDEXER="$INDEXER" python3 - <<'PYEOF'
import io
import os
import sys

SENTINEL = "# GLM52_SM12X_SPARSE_PATCHED"

def read(p):
    with io.open(p, "r", encoding="utf-8") as f:
        return f.read()

def write(p, s):
    tmp = p + ".glm52.tmp"
    with io.open(tmp, "w", encoding="utf-8") as f:
        f.write(s)
    os.replace(tmp, p)

# ---- Step A2: vllm/utils/deep_gemm.py ----
dg_path = os.environ["DEEP_GEMM"]
src = read(dg_path)
if SENTINEL in src:
    print("   deep_gemm.py already patched (sentinel present) — skipping")
else:
    helper = '''

# ---------------------------------------------------------------------------
# GLM52_SM12X_SPARSE_PATCHED: sm_12x (consumer Blackwell / GB10) fallback wiring.
# On capability family 120 there is no compiled DeepGEMM, so _lazy_init() leaves
# the *_impl globals as None and the wrappers below would call _missing() and
# raise. Instead, route the three DeepGEMM-only ops that GlmMoeDsa needs to the
# portable Triton fallbacks in
#   vllm/v1/attention/ops/deepseek_v4_ops/sm12x_deep_gemm_fallbacks.py
# (runtime-mounted by the launcher). Imported lazily so a non-sm12x image is
# unaffected and so the mount only has to exist at first call, not at import.
# ---------------------------------------------------------------------------
import functools as _glm52_functools


@_glm52_functools.cache
def _glm52_is_sm12x() -> bool:
    try:
        return bool(
            current_platform.is_cuda()
            and current_platform.is_device_capability_family(120)
        )
    except Exception:  # pragma: no cover - defensive
        return False


@_glm52_functools.cache
def _glm52_sm12x_fallbacks():
    from vllm.v1.attention.ops.deepseek_v4_ops.sm12x_deep_gemm_fallbacks import (
        _fp8_mqa_logits_sm12x,
        _fp8_paged_mqa_logits_sm12x,
        _tf32_hc_prenorm_gemm_sm12x,
    )

    return (
        _fp8_mqa_logits_sm12x,
        _fp8_paged_mqa_logits_sm12x,
        _tf32_hc_prenorm_gemm_sm12x,
    )
'''
    anchor = (
        'def _missing(*_: Any, **__: Any) -> NoReturn:\n'
        '    """Placeholder for unavailable DeepGEMM backend."""\n'
        '    raise RuntimeError(\n'
        '        "DeepGEMM backend is unavailable in the current vLLM environment, "\n'
        '        "or the available DeepGEMM package does not provide the required APIs "\n'
        '        "for these kernels."\n'
        '    )\n'
    )
    if anchor not in src:
        print("   FATAL: _missing() anchor not found in deep_gemm.py — "
              "source differs from ab66606; aborting.", file=sys.stderr)
        sys.exit(3)
    src = src.replace(anchor, anchor + helper, 1)

    mqa_gate = (
        '    _lazy_init()\n'
        '    if _fp8_fp4_mqa_logits_impl is None:\n'
        '        return _missing()\n'
        '    return _fp8_fp4_mqa_logits_impl(\n'
        '        q,\n'
        '        kv,\n'
        '        weights,\n'
        '        cu_seqlen_ks,\n'
        '        cu_seqlen_ke,\n'
        '        clean_logits=clean_logits,\n'
        '    )\n'
    )
    mqa_new = (
        '    if _glm52_is_sm12x():\n'
        '        _mqa, _paged, _hc = _glm52_sm12x_fallbacks()\n'
        '        return _mqa(q, kv, weights, cu_seqlen_ks, cu_seqlen_ke, clean_logits)\n'
        + mqa_gate
    )
    if mqa_gate not in src:
        print("   FATAL: fp8_fp4_mqa_logits gate not found — aborting.",
              file=sys.stderr)
        sys.exit(4)
    src = src.replace(mqa_gate, mqa_new, 1)

    paged_gate = (
        '    _lazy_init()\n'
        '    if _fp8_fp4_paged_mqa_logits_impl is None:\n'
        '        return _missing()\n'
        '    return _fp8_fp4_paged_mqa_logits_impl(\n'
        '        q,\n'
        '        kv_cache,\n'
        '        weights,\n'
        '        context_lens,\n'
        '        block_tables,\n'
        '        schedule_metadata,\n'
        '        max_model_len,\n'
        '        clean_logits=clean_logits,\n'
        '    )\n'
    )
    paged_new = (
        '    if _glm52_is_sm12x():\n'
        '        _mqa, _paged, _hc = _glm52_sm12x_fallbacks()\n'
        '        return _paged(\n'
        '            q, kv_cache, weights, context_lens, block_tables, max_model_len\n'
        '        )\n'
        + paged_gate
    )
    if paged_gate not in src:
        print("   FATAL: fp8_fp4_paged_mqa_logits gate not found — aborting.",
              file=sys.stderr)
        sys.exit(5)
    src = src.replace(paged_gate, paged_new, 1)

    hc_gate = (
        '    _lazy_init()\n'
        '    if _tf32_hc_prenorm_gemm_impl is None:\n'
        '        return _missing()\n'
        '    return _tf32_hc_prenorm_gemm_impl(\n'
        '        x,\n'
        '        fn,\n'
        '        out,\n'
        '        sqrsum,\n'
        '        num_split,\n'
        '    )\n'
    )
    hc_new = (
        '    if _glm52_is_sm12x():\n'
        '        _mqa, _paged, _hc = _glm52_sm12x_fallbacks()\n'
        '        return _hc(x, fn, out, sqrsum, num_split)\n'
        + hc_gate
    )
    if hc_gate not in src:
        print("   FATAL: tf32_hc_prenorm_gemm gate not found — aborting.",
              file=sys.stderr)
        sys.exit(6)
    src = src.replace(hc_gate, hc_new, 1)
    write(dg_path, src)
    print("   patched deep_gemm.py "
          "(fp8_fp4_mqa_logits, fp8_fp4_paged_mqa_logits, tf32_hc_prenorm_gemm)")

# ---- Step A3: vllm/model_executor/layers/sparse_attn_indexer.py ----
ix_path = os.environ["INDEXER"]
isrc = read(ix_path)
if SENTINEL in isrc:
    print("   sparse_attn_indexer.py already patched — skipping")
else:
    gate = (
        '        if current_platform.is_cuda() and not has_deep_gemm():\n'
        '            raise RuntimeError(\n'
        '                "Sparse Attention Indexer CUDA op requires DeepGEMM support in "\n'
        '                "the current vLLM environment."\n'
        '            )\n'
    )
    if gate not in isrc:
        print("   FATAL: SparseAttnIndexer DeepGEMM gate not found — "
              "source differs from ab66606; aborting.", file=sys.stderr)
        sys.exit(7)
    replacement = (
        '        ' + SENTINEL + '\n'
        '        # sm_12x (GB10) has no DeepGEMM package; the sparse indexer ops are\n'
        '        # served by the runtime-mounted Triton sm12x_* fallbacks instead, so\n'
        '        # do not require has_deep_gemm() on capability family 120.\n'
        '        if (\n'
        '            current_platform.is_cuda()\n'
        '            and not has_deep_gemm()\n'
        '            and not current_platform.is_device_capability_family(120)\n'
        '        ):\n'
        '            raise RuntimeError(\n'
        '                "Sparse Attention Indexer CUDA op requires DeepGEMM support in "\n'
        '                "the current vLLM environment."\n'
        '            )\n'
    )
    isrc = isrc.replace(gate, replacement, 1)
    write(ix_path, isrc)
    print("   patched sparse_attn_indexer.py (SparseAttnIndexer constructor gate)")

import py_compile
for p in (dg_path, ix_path):
    py_compile.compile(p, doraise=True)
print("   py_compile OK for both patched files")
PYEOF

# ---------------------------------------------------------------------------
# Step A4 — route sm_12x (GB10) DECODE top-k off persistent_topk.
# STANDALONE + sentinel-guarded (NOT nested in A2/A3, whose sentinel may already
# be present). On GB10 the DSA decode indexer calls torch.ops._C.persistent_topk
# over a logits row of width stride=max_model_len; once max_model_len pushes
# total_ctas=ceil(max_model_len/8472) past num_sms*occupancy=48 (i.e. ~>397k:
# 31@256k ok, 62@512k, 124@1M) the cooperative path "would oversubscribe" and the
# FilteredTopK fallback needs >=128KB smem vs GB10's 99KB -> RuntimeError, killing
# decode at 512k/1M. The in-tree `else` branch (ops.top_k_per_row_decode) is the
# set-equivalent radix top-k: one block/row, ~8KB smem, no SM/smem wall. We only
# stop cap-family 120 from taking the persistent path.
# ---------------------------------------------------------------------------
INDEXER="$INDEXER" python3 - <<'PYEOF'
import io, os, sys
SENT = "# GLM52_SM12X_DECODE_REROUTE"
ix = os.environ["INDEXER"]
with io.open(ix, "r", encoding="utf-8") as f:
    s = f.read()
anchor = "        if current_platform.is_cuda() and topk_tokens in (512, 1024, 2048):\n"
if SENT in s:
    print("   A4: sm_12x decode reroute already applied — skipping")
elif anchor not in s:
    print("   FATAL A4: persistent_topk decode gate anchor not found in "
          "sparse_attn_indexer.py — source differs from ab66606; aborting.",
          file=sys.stderr)
    sys.exit(8)
else:
    new = (
        "        " + SENT + " (GB10 cap-family 120 cannot run persistent_topk at\n"
        "        # long context; take the set-equivalent top_k_per_row_decode else-branch)\n"
        "        if (\n"
        "            current_platform.is_cuda()\n"
        "            and topk_tokens in (512, 1024, 2048)\n"
        "            and not current_platform.is_device_capability_family(120)\n"
        "        ):\n"
    )
    s = s.replace(anchor, new, 1)
    tmp = ix + ".glm52a4.tmp"
    with io.open(tmp, "w", encoding="utf-8") as f:
        f.write(s)
    os.replace(tmp, ix)
    import py_compile
    py_compile.compile(ix, doraise=True)
    print("   A4: routed sm_12x decode to top_k_per_row_decode; py_compile OK")
PYEOF

echo "== glm52-sm12x-sparse: done"

# ===========================================================================
# STEP B — glm52-b12x-sparse  (b12x decode MLA; cudagraph-mode decided by probe)
# ===========================================================================
echo "== glm52-b12x-sparse: installing b12x==$B12X_VERSION (--no-deps)"

# Idempotent: only install if the right version is not already importable.
if python3 -c "import b12x, sys; sys.exit(0 if getattr(b12x,'__version__','') == '$B12X_VERSION' else 1)" 2>/dev/null; then
  echo "   b12x==$B12X_VERSION already installed"
else
  # --no-deps is MANDATORY: b12x's Requires-Dist would pull/upgrade
  # nvidia-cutlass-dsl / torch / transformers and clobber the pinned stack.
  # Prefer an offline wheel staged in the image/mount; fall back to PyPI.
  if ! pip install --no-deps --no-index \
        --find-links "${GLM52_B12X_WHEEL_DIR:-/models/wheels}" "b12x==$B12X_VERSION" 2>/dev/null; then
    echo "   (no offline wheel; fetching b12x==$B12X_VERSION from PyPI)"
    pip install --no-deps "b12x==$B12X_VERSION"
  fi
fi

# PROBE the REAL decode imports (not just `import b12x`). The missing-b12x
# warning in b12x_sparse_helpers.py is warning_once and is suppressed after
# prefill warmup, so a FULL run that THINKS b12x is present but isn't would only
# crash at the first decode capture. Decide cudagraph mode from this probe.
if python3 -c "import b12x.attention.mla.prefill_mg, b12x.attention.mla.traits" 2>/dev/null; then
  GLM52_B12X_MLA_RESULT=1
  GLM52_CUDAGRAPH_MODE_RESULT=FULL
  echo "   b12x decode imports OK -> GLM52_B12X_MLA=1, cudagraph FULL"
else
  GLM52_B12X_MLA_RESULT=0
  GLM52_CUDAGRAPH_MODE_RESULT=PIECEWISE
  echo "   WARNING: b12x decode import FAILED -> GLM52_B12X_MLA=0, cudagraph PIECEWISE" >&2
fi

# Persist the probe result so the launcher's `vllm serve` can source it and pick
# the cudagraph mode from REAL import success rather than an assumed env var.
{
  printf 'GLM52_B12X_MLA=%s\n' "$GLM52_B12X_MLA_RESULT"
  printf 'GLM52_CUDAGRAPH_MODE=%s\n' "$GLM52_CUDAGRAPH_MODE_RESULT"
} > "$B12X_ENV_OUT"
echo "   wrote $B12X_ENV_OUT"

# fused_indexer score-mode patch INTENTIONALLY OMITTED (see header). NSA_RELU_SUM
# / TOKEN_LOGITS is the target if you wire b12x.attention.indexer later.

# ===========================================================================
# STEP C — glm52-nvfp4-moe-backend  (NVFP4-only: force MARLIN on sm_12x/GB10)
# The FLASHINFER_CUTLASS NvFP4 MoE routes into TRT-LLM cutlass_fused_moe and
# intermittently raises a CUDA IMA in cudaMemsetAsync(final_output) (CUTLASS
# #2906/#3096) -> kills EngineCore. VLLM_CUTLASS shares the SAME broken SM120
# block-scaled grouped-GEMM templates -> ~5 tok/s GARBAGE. Strip BOTH from the
# NvFP4 auto-select list on capability-family 120 so it lands on MARLIN (w4a16:
# dequantizes the FP4 weights in-GEMM with bf16 activations, never touches the
# broken FP4 grouped-GEMM; correct + stable on consumer Blackwell; vLLM already
# falls MXFP8 MoE back to Marlin on sm_121). Touches ONLY oracle/nvfp4.py -> the
# unquantized in-checkpoint MTP MoE (oracle/unquantized.py) is unaffected (that
# is why the global `--moe-backend marlin` flag fails and this surgical edit
# works). Idempotent (sentinel GLM52_NVFP4_MOE_BACKEND), FATAL on missing anchor.
# ===========================================================================
NVFP4_ORACLE="$VLLM/model_executor/layers/fused_moe/oracle/nvfp4.py"
NVFP4_ORACLE="$NVFP4_ORACLE" python3 - <<'PYEOF'
import io, os, sys
SENTINEL = "# GLM52_NVFP4_MOE_BACKEND"
path = os.environ["NVFP4_ORACLE"]
with io.open(path, "r", encoding="utf-8") as f:
    src = f.read()
if SENTINEL in src:
    print("   nvfp4.py already patched (GLM52_NVFP4_MOE_BACKEND) — skipping")
    sys.exit(0)

anchor = (
    '    """\n'
    '    Select the primary NvFP4 MoE backend\n'
    '    Note: Shape-specific fallbacks may still occur at runtime.\n'
    '    """\n'
    '\n'
    '    # NOTE: the kernels are selected in the following order.\n'
)
if anchor not in src:
    print("   FATAL: select_nvfp4_moe_backend docstring anchor not found — "
          "source differs from ab66606; aborting.", file=sys.stderr)
    sys.exit(3)
inject = (
    '    """\n'
    '    Select the primary NvFP4 MoE backend\n'
    '    Note: Shape-specific fallbacks may still occur at runtime.\n'
    '    """\n'
    '\n'
    '    ' + SENTINEL + ': on sm_12x (GB10, capability family 120) BOTH the\n'
    '    # FlashInfer NvFP4 MoE path (TRT-LLM cutlass_fused_moe -> intermittent\n'
    '    # CUDA IMA in cudaMemsetAsync(final_output)) AND the in-tree VLLM_CUTLASS\n'
    '    # path (same broken SM120 grouped-GEMM -> garbage) are unsafe. Strip them\n'
    '    # from auto-selection so the NvFP4 MoE lands on MARLIN. Auto-select only;\n'
    '    # an explicit moe_backend= request is honored unchanged.\n'
    '    from vllm.platforms import current_platform as _glm52_cp\n'
    '    _glm52_strip_unsafe_fam120 = (\n'
    '        config.moe_backend == "auto"\n'
    '        and _glm52_cp.is_cuda()\n'
    '        and _glm52_cp.is_device_capability_family(120)\n'
    '    )\n'
    '\n'
    '    # NOTE: the kernels are selected in the following order.\n'
)
src = src.replace(anchor, inject, 1)

list_anchor = (
    '        NvFp4MoeBackend.EMULATION,\n'
    '    ]\n'
    '\n'
    '    NVFP4_BACKENDS_WITH_CLAMP = {\n'
)
if list_anchor not in src:
    print("   FATAL: AVAILABLE_BACKENDS list-end anchor not found — aborting.",
          file=sys.stderr)
    sys.exit(4)
list_inject = (
    '        NvFp4MoeBackend.EMULATION,\n'
    '    ]\n'
    '\n'
    '    if _glm52_strip_unsafe_fam120:\n'
    '        _glm52_unsafe = set(FLASHINFER_NVFP4_MOE_BACKENDS) | {\n'
    '            NvFp4MoeBackend.VLLM_CUTLASS,\n'
    '        }\n'
    '        AVAILABLE_BACKENDS = [\n'
    '            b for b in AVAILABLE_BACKENDS if b not in _glm52_unsafe\n'
    '        ]\n'
    '\n'
    '    NVFP4_BACKENDS_WITH_CLAMP = {\n'
)
src = src.replace(list_anchor, list_inject, 1)

tmp = path + ".glm52c.tmp"
with io.open(tmp, "w", encoding="utf-8") as f:
    f.write(src)
os.replace(tmp, path)
import py_compile
py_compile.compile(path, doraise=True)
print("   nvfp4.py patched: FLASHINFER_* + VLLM_CUTLASS stripped on fam120 -> MARLIN; py_compile OK")
PYEOF

echo "== glm52-runtime-patch: done"

# ---- cyber-ablation arming: inject ensure_hooks into DeepseekV2Model.forward (reliable, in-place) ----
SP=$(python3 -c "import site;print(site.getsitepackages()[0])")
cp /models/cyber/ablation_patch.py "$SP/ablation_patch.py"
python3 - <<'PYEOF'
import os
V=os.popen("python3 -c 'import vllm,os;print(os.path.dirname(vllm.__file__))'").read().strip()
F=os.path.join(V,"model_executor/models/deepseek_v2.py")
src=open(F).read()
if "_ab.ensure_hooks" in src:
    print("[cyber-ablation] ensure_hooks already injected"); raise SystemExit
cls=src.index("class DeepseekV2Model")
i=src.index("for idx, layer in enumerate(", cls)
ls=src.rfind("\n",0,i)+1
indent=src[ls:i]
inj=("%stry:\n%s    import ablation_patch as _ab; _ab.ensure_hooks(self)\n%sexcept Exception:\n%s    pass\n"
     % (indent,indent,indent,indent))
open(F,"w").write(src[:ls]+inj+src[ls:])
print("[cyber-ablation] injected ensure_hooks into DeepseekV2Model.forward (%s)" % F)
PYEOF
